# filepath: c:\Users\omidm\FinanceFlow\.github\ISSUE_TEMPLATE\config.yml
blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/your-repo/your-repo/issues/new?template=general-question.md
    about: Ask a general question about the project.
issue_templates:
  - name: Task
    description: Use this template for task-related issues.
    title: "[TASK] "
    labels: ["task"]
    assignees: []
    template: task.md
  - name: Suggestion
    description: Use this template for suggesting new features.
    title: "[SUGGESTION] "
    labels: ["suggestion"]
    assignees: []
    template: suggestion.md
    